### ISSUE TITLE
Add a NetCDF file info tool

### ISSUE THREAD

**Issue by jayeshkrishna** [E3SM-Project/scorpio#104]
Add a utility in PIO that provides information
including compatibility wrt underlying I/O
libraries.
Some information that can be included in the
output are:
1) NetCDF version of the file
2) File readable/writeable by the different I/O
    libraries
3) Other basic info on the file

**Comment by jayeshkrishna** [comment]
@dqwu : Please add your thoughts on this tool (what other outputs would be useful to the user etc)

**Comment by rljacob** [comment]
"underlying I/O libraries" means things like netcdf4, pnetcdf that might be compiled in with PIO?

**Comment by rljacob** [comment]
Somewhat related, could PIO write out a helpful message when its initialized about what low level libraries it has been configured with?

**Comment by jayeshkrishna** [comment]
There is another issue for a pio config tool - https://github.com/E3SM-Project/ParallelIO/issues/105 , that can print out that information.

**Comment by ndkeen** [comment]
The one thing I was hoping for is a tool that could read a netcdf file to verify if there are any issues. We have ncdump -k which works as a bare minimum. Ideally would be nice to have a way to read the file in a manner that is most like the way it would be read by e3sm in a typical simulation. But anything in between could be useful. The use case would be to debug -- if tool can't read file, likely e3sm cannot.  If there is an issue in e3sm and tool can read file, maybe good chance something else is wrong.

**Comment by jayeshkrishna** [comment]
Thanks, yes that would be the typical use case for the tool.
