### ISSUE TITLE
Rename pio config header

### ISSUE THREAD

**Issue by jayeshkrishna** [E3SM-Project/scorpio#140]
The PIO config header is named "config.h" . Using
a generic name for the config header can be
problematic when building PIO as part of another
software (like E3SM) where potentially other libraries
could use the same name for config headers.

We could rename "config.h" to "pio_config.h" to avoid
any name conflicts.

**Comment by jayeshkrishna** [comment]
@dqwu : Any thoughts?

**Comment by dqwu** [comment]
@jayeshkrishna 
I am OK with this change, it is always good to avoid potential name conflicts.
