### ISSUE TITLE
Scorpio retry message

### ISSUE THREAD

**Issue by rljacob** [E3SM-Project/scorpio#267]
@amametjanov showed me a log message when a file open doesn't work:

" 0: PIO: WARNING: Opening file (/home/ccsm-data/inputdata/atm/cam/chem/trop_mozart_aero/emis/DECK_ne30/cmip6_mam4_num_a4_elev_1850-2014_c170525.nc) with iotype=1 failed. Switching iotype to PIO_IOTYPE_NETCDF
"
A request and a question:
Is the IOTYPE changed for the rest of the run or just for that file?

In addition to "iotype=1" can you print the type as a string like "pnetcdf" ?

**Comment by jayeshkrishna** [comment]
Yes, I agree the error message needs to be fixed to include human readable names.

**Comment by jayeshkrishna** [comment]
Scorpio message is clearer. This issue should be fixed in scorpio classic.

**Comment by jayeshkrishna** [comment]
A failure to read a NetCDF4 input file is a very common case, we should provide as much information as possible to the user.

Also see related Issue #262

**Comment by rljacob** [comment]
What about my question?  Is the IOTYPE changed for the rest of the run or just for that file?

**Comment by jayeshkrishna** [comment]
The IOTYPE is change for just that file (not for the rest of the run).

**Comment by dqwu** [comment]
For the warning message, scorpio uses pio_iotype_to_string() to convert type enum values to type names. Apparently this feature has not been ported to scorpio classic yet.

For both scorpio and scorpio classic, the type change is made inside the file descriptor structure, so it is just for the file.
