### ISSUE TITLE
classic vs "regular"

### ISSUE THREAD

**Issue by pwolfram** [E3SM-Project/scorpio#308]
Can someone please tell me what the difference between scorpio v1.10.0 "regular" and classic entails?  For some reason, this pio1.X version is registering in MPAS-O as PIO2, which seems strange to me.  Should I be building instead with PIO2?  I'm having substantial issues with migration to newer versions of PIO, see https://github.com/MPAS-Dev/MPAS-Model/issues/576

Thanks to @wkliao for recommending a move away from openmpi, which I can try now to migrate instead to intel's version.

**Comment by jayeshkrishna** [comment]
The Scorpio classic library (PIO_VERSION=1) is the older version of the library implemented in Fortran. The Scorpio library (PIO_VERSION=2)  is the latest version of the library implemented in C and uses different (more optimized) algorithms for I/O. Both version of libraries should support the same Fortran API.
Can you add information here (in the issue description) on how to recreate the latest issue that you have with Scorpio?

**Comment by pwolfram** [comment]
@jayeshkrishna, this is extremely helpful, thank you!  

If I understand correctly, PIO2 would be better to use, minimally for I/O performance reasons.  In the long past, MPAS-O effectively only worked for PIO1, but this has changed more recently.  I'm inclined to go the PIO2 route - noting that since I'm *not* using "classic" should designate modules as `pio2` instead of `pio`.   Is there real deviation from NCAR's pio effort?  Clearly the software engineering here is much better but I'm assuming API is likely similar and (cc @philipwjones) we will support Scorpio not ParallelIO in the future for E3SM / MPAS-O.

Based on MPAS-Dev/MPAS-Model#576, I'm not currently sure if this is a Scorpio issue or rather yet another bad open-mpi issue, which @wkliao suggests is related to open-mpi, e.g., errors like 

```
libmpi.so.20.10.2  00002B7C9F1C6A72  ADIOI_LUSTRE_Get_     Unknown  Unknown
libmpi.so.20.10.2  00002B7C9F1C8764  ADIOI_LUSTRE_Writ     Unknown  Unknown
libmpi.so.20.10.2  00002B7C9F1F3D68  MPIOI_File_write_     Unknown  Unknown
libmpi.so.20.10.2  00002B7C9F1F4552  mca_io_romio314_d     Unknown  Unknown
```

I've decided given we have intel / intel mpi builds of everything but Scorpio (e.g., netcdf, hdf5, pnetcdf) to go with that to get MPAS-O to work and will document at  MPAS-Dev/MPAS-Model#576).

Are you aware of any issues with Scropio with that type of stack?

Will report back here with my results and am hoping this resolves the issue.

**Comment by jayeshkrishna** [comment]
Ok, Scorpio should work fine with Intel MPI and NetCDF/HDF5/PnetCDF. I would recommend looking at the versions of these libraries on other systems (if the system you are trying on does not have a configuration in E3SM config_machines.xml) to see which libraries to build/install.

Scorpio and PIO support the same Fortran API and the applications should build with both the libraries without any modifications. I would recommend using Scorpio to build/test your case initially since its tested/supported on all machines of interest to E3SM (after getting it to work you can try out PIO2 too, if you wanted to)

**Comment by pwolfram** [comment]
Thanks, this helped yield the solution: https://github.com/MPAS-Dev/MPAS-Model/pull/592.
