### ISSUE TITLE
Load balancing issue with default SUSBET partition

### ISSUE THREAD

**Issue by dqwu** [E3SM-Project/scorpio#311]
When creating the MPI communicators needed by the SUBSET rearranger, the default partition is implemented with following algorithm:
 ```
   if (ios->ioproc)
    {
        key = 0;
        color= ios->io_rank;
    }
    else
    {
        int taskratio = ios->num_comptasks / ios->num_iotasks;
        key = max(1, ios->comp_rank % taskratio + 1);
        color = min(ios->num_iotasks - 1, ios->comp_rank / taskratio);
    }
```
This algorithm works with good load balancing when the number of compute tasks is divisible by the number of IO tasks.

For 16 compute tasks, 4 IO tasks (rank = 0, 4, 8, 12), the partition is shown as below.
Each IO task is assigned 4 compute tasks.
```
rank = 0, key = 0, color = 0
rank = 1, key = 2, color = 0
rank = 2, key = 3, color = 0
rank = 3, key = 4, color = 0

rank = 4, key = 0, color = 1
rank = 5, key = 2, color = 1
rank = 6, key = 3, color = 1
rank = 7, key = 4, color = 1

rank = 8, key = 0, color = 2
rank = 9, key = 2, color = 2
rank = 10, key = 3, color = 2
rank = 11, key = 4, color = 2

rank = 12, key = 0, color = 3
rank = 13, key = 2, color = 3
rank = 14, key = 3, color = 3
rank = 15, key = 4, color = 3
```
However, when the number of compute tasks is not divisible by the number of IO tasks, the load balancing might be poor with this algorithm. It has already caused some performance issues for E3SM production runs with SUBSET rearranger.

For 15 compute tasks, 4 IO tasks (rank = 0, 4, 8, 12), the partition is shown as below.
The last IO task is assigned 6 compute task, while other IO tasks are assigned 3.

```
rank = 0, key = 0, color = 0
rank = 1, key = 2, color = 0
rank = 2, key = 3, color = 0

rank = 4, key = 0, color = 1
rank = 3, key = 1, color = 1
rank = 5, key = 3, color = 1

rank = 8, key = 0, color = 2
rank = 6, key = 1, color = 2
rank = 7, key = 2, color = 2

rank = 12, key = 0, color = 3
rank = 9, key = 1, color = 3
rank = 10, key = 2, color = 3
rank = 11, key = 3, color = 3
rank = 13, key = 2, color = 3
rank = 14, key = 3, color = 3
```
Since 15 / 4 = 3 and 15 % 4 = 3, the algorithm might as well assign the extra 3 compute tasks evenly to the first 3 IO tasks to achieve a better load balancing.

**Comment by jayeshkrishna** [comment]
We might want to divide the processes such that I/O processes get a contiguous range of MPI processes. 
So in this case,

```
rank = 0, key = 0, color = 0
rank = 1, key = 1, color = 0
rank = 2, key = 2, color = 0
rank = 3, key = 3, color = 0

rank = 4, key = 0, color = 1
rank = 5, key = 1, color = 1
rank = 6, key = 2, color = 1
rank = 7, key = 3, color = 1

rank = 8, key = 0, color = 2
rank = 9, key = 1, color = 2
rank = 10, key = 2, color = 2
rank = 11, key = 3, color = 2

rank = 12, key = 0, color = 3
rank = 13, key = 1, color = 3
rank = 14, key = 2, color = 3
```
