### ISSUE TITLE
oom issues on Cori at NE256

### ISSUE THREAD

**Issue by mt5555** [E3SM-Project/scorpio#330]
Running NE256 on Cori with 1024 nodes, 32x4. (32 MPI tasks, each with 4 threads).
This configuration will run on as few as 256 nodes, so I dont think it's at the edge of memory usage.
A couple things with SCORPIO:

when adding an "h1" file with high frequency output of about 5 3d variables: when writing 60 snapshots per file I got oom errors when closing the file.  Lowering this to 10 snapshots per file worked.   Is there some internal cacheing in SCORPIO?  and is there a way to reduce this?

With restart, maybe a related issue:  running 1 month and writing a restart at the end of the month worked.  But then running 2 months and writing a restart at the end of 2 months gave OOM errors when writing the restart file. 

Traceback information for that suggests that many of the processers are in PIOc_sync(), called from restart_dynamics().  Some of the tasks have gotten further (presumably the non I/O writers) and are in PIOc_initdecomp()

```
 1216: e3sm.exe           00000000033FD72A  Unknown               Unknown  Unknown
 1216: e3sm.exe           000000000337331E  piolib_mod_mp_fre         983  piolib_mod.F90
 1216: e3sm.exe           0000000001C672C6  restart_dynamics_         324  restart_dynamics.F90
 1216: e3sm.exe           0000000000543893  cam_restart_mp_ca         240  cam_restart.F90
 1216: e3sm.exe           00000000004FF934  cam_comp_mp_cam_r         389  cam_comp.F90
 1216: e3sm.exe           00000000004EB886  atm_comp_mct_mp_a         562  atm_comp_mct.F90
 1216: e3sm.exe           0000000000422D69  component_mod_mp_         737  component_mod.F90
 1216: e3sm.exe           000000000040442B  cime_comp_mod_mp_        2820  cime_comp_mod.F90
 1216: e3sm.exe           0000000000422953  MAIN__                    133  cime_driver.F90
 1216: e3sm.exe           0000000000401F72  Unknown               Unknown  Unknown
 1216: e3sm.exe           000000000500E64F  Unknown               Unknown  Unknown
 1216: e3sm.exe           0000000000401E5A  Unknown               Unknown  Unknown

```

```
22540: e3sm.exe           0000000003374704  piolib_mod_mp_pio         597  piolib_mod.F90
22540: e3sm.exe           000000000057E035  cam_grid_support_         635  cam_grid_support.F90
22540: e3sm.exe           000000000057DCBD  cam_grid_support_        2378  cam_grid_support.F90
22540: e3sm.exe           0000000001A79CCA  restart_physics_m         249  restart_physics.F90
22540: e3sm.exe           00000000005438CC  cam_restart_mp_ca         244  cam_restart.F90
22540: e3sm.exe           00000000004FF934  cam_comp_mp_cam_r         389  cam_comp.F90
22540: e3sm.exe           00000000004EB886  atm_comp_mct_mp_a         562  atm_comp_mct.F90
22540: e3sm.exe           0000000000422D69  component_mod_mp_         737  component_mod.F90
22540: e3sm.exe           000000000040442B  cime_comp_mod_mp_        2820  cime_comp_mod.F90
22540: e3sm.exe           0000000000422953  MAIN__                    133  cime_driver.F90
22540: e3sm.exe           0000000000401F72  Unknown               Unknown  Unknown
22540: e3sm.exe           000000000500E64F  Unknown               Unknown  Unknown
```

**Comment by mt5555** [comment]
I think pio_initdecomp() could be using a lot of memory - and these processers are all stuck waiting for the I/O tasks anyway.  Would it help to have a barrier after restart_dynamics() and after restart_physics()?  So that the non-I/O tasks are not allocating large arrays while data is still being written (IIRC, most of the data is written during hte pioc_sync() call).

**Comment by jayeshkrishna** [comment]
The first thing to try would be to check the size of PIO_BUFFER_SIZE_LIMIT (the size of the cache used by Scorpio to buffer data), and see if its too high.

**Comment by mt5555** [comment]
<entry id="PIO_BUFFER_SIZE_LIMIT" value="134217728">

128M

**Comment by jayeshkrishna** [comment]
This is the buffer size per MPI process, I would recommend trying a slightly lower value (100 MB and then 64 MB) and see if the issue persists.

**Comment by mt5555** [comment]
Restart run with PIO_BUFFERS_SIZE_LIMIT set to 96MB, writing restart monthly:

1st restart worked
2nd restart crashed with oom error, stack trace same as above.

**Comment by jayeshkrishna** [comment]
ok, thanks for trying out the lower setting for the buffer size. We will take a look at this case and let you know what we find.

**Comment by jayeshkrishna** [comment]
@mt5555 Do you have a run script or more information (create_newcase command + user_nl_cam) on how to run this case?

**Comment by mt5555** [comment]
I switched to a 5 day test case, writing a restart after every day.
./xmlchange PIO_BUFFER_SIZE_LIMIT=67108864

This case worked - it wrote all 5 restart files and then exited normally.    I changed two things (short run and PIO buffer).  I'll repeat this test with the 128M buffer.

**Comment by mt5555** [comment]
to run this configuration, see NE256 real planet section here:

https://acme-climate.atlassian.net/wiki/spaces/NGDNA/pages/1683783740/HV+tuning+configurations

however, let me try and isolate it further - since it looks like its not a SCORPIO issue.

**Comment by mt5555** [comment]
update: successful runs:
PIO_BUFFER 64MB, write restart every day for 5 days.
PIO_BUFFER 128MB, write restart every day for 5 days.
PIO_BUFFER 128MB, write restart after 1 month.

unsuccessful runs:
PIO_BUFFER 128MB, write restart after 2 months crashed (OOM)
PIO_BUFFER 96MB, month 1 restart ok, month 2 restart crashed (OOM)

one difference between the long and short runs is the cam.h0 file (default written monthly).  I'm going to change the short run to write the cam.h0 file daily to see if that triggers the oom errors in the short runs.

**Comment by ndkeen** [comment]
I can try to plot memory use over time if that helps

**Comment by mt5555** [comment]
Noel - I think it would be useful if you could first run a NE30 compset that mimics this (tri-grid, theta-l dycore, SCORPIO I/O) and see if there are any memory leaks that have crept in since you last did those kind of checks?

**Comment by dqwu** [comment]
@mt5555 
From all of your unsuccessful runs with OOM, could you please pick one that uses least compute resources and share its case directory and run directory on Cori? We will first try to reproduce the OOM issue.

**Comment by mt5555** [comment]
Adding some additional information for the record:

I attempted to make two additional 2 month runs at NE256.  The first run was using SCREAM's 128L and I forgot to set the lfs stripe, so it was slower then anticipated and ran out of time after 1.5 months, so didn't get to test this issue (restart after 2 months).  The second run was (using the orignal 72L configuration) to test this issue and also model stability of tstep_type=9: it crashed after 20 days due to an instability in the sponge layer.   

one additional data point: going from 72L to 128L caused the atm/land MPI tasks to run out of memory.  As the only change was increasing the memory of the 3D distributed variables in the atmosphere, this confirms that the original configuration was using close to the limit of the nodes memory.  

Taking into consideration that these runs are expensive (1M core hours each) and the fact that restart after 1 month works, and multtiple daily restarts work, I think we should put this issue on hold for now.
