### ISSUE TITLE
Replace CMAKE_SOURCE_DIR with SCORPIO_SOURCE_DIR (similarly for BINARY)

### ISSUE THREAD

**Issue by bartgol** [E3SM-Project/scorpio#342]
CMake variables available:
```
CMAKE_SOURCE_DIR : The path to the top level of the source tree
CMAKE_BINARY_DIR : The path to the top level of the build tree
PROJECT_SOURCE_DIR : Top level source directory for the current cmake project
PROJECT_BINARY_DIR : Full path to build directory for the current cmake project
<PROJECT-NAME>_SOURCE_DIR : Top level source directory for the cmake project, <PROJECT-NAME>
<PROJECT-NAME>_BINARY_DIR : Full path to build directory for the cmake project, <PROJECT-NAME>
```
Scorpio currently uses `CMAKE_[SOURCE|BINARY]_DIR` for referring to directories in CMake build scripts. The ```CMAKE_SOURCE_DIR```, for example, always refers to the top-most cmake project directory. If another application/library uses scorpio via `add_subdirectory(/path/to/scorpio)`, the build system breaks (since all references to `CMAKE_[SOURCE|BINARY]_DIR` in the Scorpio build scripts now refer to the top level of the source tree of the application using Scorpio, instead of the top level of the source tree of Scorpio).

Notice that, once `project(...)` is called in the CMake build scripts, the variables `${PROJECT_NAME}_SOURCE_DIR` and `${PROJECT_NAME}_BINARY_DIR` are available. If the project is built in standalone mode, they match the content of `CMAKE_SOURCE_DIR` and `CMAKE_BINARY_DIR`. If the project is built _within_ another cmake project the formers are safer than the latters. Scorpio already has a parent project, called SCORPIO, and hence `SCORPIO_[SOURCE|BINARY]_DIR` can safely be used in the build scripts instead of `CMAKE_[SOURCE|BINARY]_DIR` .

Context: SCREAM is trying to use scorpio also in a standalone build. This would allow us to test our I/O infrastructure during every single PR. All the tpls in SCREAM are currently added with `add_subdirectory`, but we are forced to add scorpio via `ExternalProject_Add`.

Note: the discussion `add_subdirectory` vs `ExternalProject_Add` is quite old, and will likely continue. I understand that our problem goes away by simply using `ExternalProject_Add`; however, it'd be nice if SCORPIO supported also the other approach, especially since it boils down to a simple find-and-replace.

We can help, if needed.

**Comment by jayeshkrishna** [comment]
We are fine with changing this if it makes your life easier. Any specific reasons ExternalProject_Add does not work for you?

Also, do you know the version PROJECT_[SOURCE|BINARY]_DIR was added to cmake (Was it in 3.0.2+ or available in 2.8)?

**Comment by bartgol** [comment]
If the cmake project provides a <PackageName>Config.cmake config script, then I may be fine with ExternalProject_Add. This is unfortunately not often the case. And if so, there are a few issues:

1) one needs to know a priori where the libs will be built. 
2) to write good cmake, one probably wants to wrap those libs in an imported target, to propagate include directories, link/compile flags, etc. Which is more cmake to write (and imported target can be confusing for some people).
3) if the project has dependencies, one needs to find them, and link them to the imported targets (so that they are propagated).

Using add_subdirectory, things are a bit easier: target are already visible from the host project, and already have all the compile/link properties attached.

As for the version of cmake that supports <PROJECT_NAME>_xyz_DIR, I tried with an installation of 2.8.12 and it was working. I don't know exactly when it started to be available. Do you need a specific cmake version?

**Comment by jayeshkrishna** [comment]
Ok, as long as its working with 2.8.12 its fine (that is our pre req right now). I have found it hard to find the exact version of cmake when a particular feature was introduced.

**Comment by bartgol** [comment]
Yeah, cmake online (decent) documentation stops at 3.0.2. Checking if a feature is available for all 3.x versions is easy (change version while on the feature page till it disappears), but before 3.0.2 the trick doesn't work, and it becomes quite hard.
