### ISSUE TITLE
Stop GPTL timers in all error cases

### ISSUE THREAD

**Issue by jayeshkrishna** [E3SM-Project/scorpio#350]
Scorpio returns an error code back to the user when a Scorpio call/API fails. Unless the user requests that Scorpio handle errors internally (error handler is set to PIO_INTERNAL_ERROR), the user is free to ignore the error code and continue. Although the GPTL timers are stopped correctly for the non-error cases (and for APIs where an error is not considered fatal, e.g. inquiring an attribute on a file can fail but it is not a fatal error) the timers are not stopped for the error cases. If the timer is not stopped the timer data collected by GPTL is not valid (the unstopped calls look recursive since the timers are not stopped and the parent-child relationship between the timers are incorrect)

So we need to stop GPTL timers in all error cases

Also see issue #348

**Comment by worleyph** [comment]
Just to expand on the error. The fact that the unstopped timer is marked as a recurvive call is not the primary problem (though it is annoying). It also marks all subsequent timer calls as children of this timer, so the timer parent/child relationship is corrupted. Calls to the unstopped timer at different locations may also be "confused" - not really sure whether the information is valid or not.
