### ISSUE TITLE
ArgParser throws an instance of std::regex_error with IBM XL compiler

### ISSUE THREAD

**Issue by dqwu** [E3SM-Project/scorpio#356]
The ArgParser is used by the ADIOS conversion tool and other tools in Scorpio. Scorpio built with IBM XL compiler on Summit throws a std::regex_error exception when running the ADIOS conversion tool. The tool works (does not throw the exception) with other machines+compilers (looks like the issue is specific to the IBM compiler).

test_regex.cpp (a stripped down version of the code in ArgParser) is a simple C++ program to reproduce this issue on Summit with default XL compiler (reproducible with latest xl/16.1.1-8)
```
#include <iostream>
#include <string>
#include <regex>

using namespace std;

int main(int argc, char *argv[])
{
  const std::string OPT_RGX_STR("--([^=]+)=(.+)");

  for (int i = 1; i < argc; i++){
    std::regex opt_rgx(OPT_RGX_STR.c_str());
    std::smatch match;
    std::string argvi(argv[i]);

    regex_search(argvi, match, opt_rgx);

    cout << "match.size() = " << match.size() << endl;
  }

  return 0;
}
```
On a login node of Summit, build and run this program with default XL compiler
```
xlc++_r test_regex.cpp -std=c++11
./a.out --help
```
The output is
```
terminate called after throwing an instance of 'std::regex_error'
  what():  regex_error
Aborted (core dumped)
```

**Comment by dqwu** [comment]
Not reproducible with g++ (GCC) 6.4.0 on Summit
```
module load gcc
g++ test_regex.cpp -std=c++11
./a.out --help
```
The output is
`match.size() = 0`

**Comment by dqwu** [comment]
Reproducible with default g++ (GCC) 4.8.5 on Summit.
Also reproducible with PGI 19.9 on Summit.
Maybe XL/PGI compiler uses g++ (GCC) 4.8.5 by default?

**Comment by jayeshkrishna** [comment]
It looks like the issue is due to limited support for regex in the compiler. The exception is thrown while the regex object is created, so the following smaller code should recreate the exception,

```
#include <iostream>
#include <string>
#include <regex>

using namespace std;

int main(int argc, char *argv[])
{
  const std::string OPT_RGX_STR("--([^=]+)=(.+)");
  std::regex opt_rgx(OPT_RGX_STR.c_str());

  return 0;
}
```
Still debugging and working on a fix

**Comment by dqwu** [comment]
This issue is reproducible with gcc/4.8.5 on Summit, but not reproducible with gcc/5.4.0

It is also confirmed that both XL and PGI C++ compilers use gcc/4.8.5 by default on Summit.

```
module load xl
xlc++_r -v test_regex.cpp -std=c++11
exec: export(export,XL_CONFIG=/sw/summit/xl/16.1.1-5/xlC/16.1.1/etc/xlc.cfg.rhel.7.6.gcc.4.8.5.cuda.10.1:xlc++_r,NULL)
...

module load pgi
pgc++ -v test_regex.cpp -std=c++11
Export PGI_CURR_CUDA_HOME=/autofs/nccs-svm1_sw/summit/.swci/0-core/opt/spack/20180914/linux-rhel7-ppc64le/gcc-4.8.5/pgi-19.9-6rlh73dtf3lmbm6v7r3fkh7tnbeq53hc/linuxpower/2019/cuda/
Export PGI=/autofs/nccs-svm1_sw/summit/.swci/0-core/opt/spack/20180914/linux-rhel7-ppc64le/gcc-4.8.5/pgi-19.9-6rlh73dtf3lmbm6v7r3fkh7tnbeq53hc
...
```

**Comment by dqwu** [comment]
It has been confirmed that regex is not implemented before GCC 4.9.0
https://gcc.gnu.org/bugzilla/show_bug.cgi?id=53631

**Comment by dqwu** [comment]
A snippet to detect if the libstdc++ implementation supports regex.
From https://stackoverflow.com/questions/12530406/is-gcc-4-8-or-earlier-buggy-about-regular-expressions 
```
#include <regex>
#if __cplusplus >= 201103L &&                             \
    (!defined(__GLIBCXX__) || (__cplusplus >= 201402L) || \
        (defined(_GLIBCXX_REGEX_DFS_QUANTIFIERS_LIMIT) || \
         defined(_GLIBCXX_REGEX_STATE_LIMIT)           || \
             (defined(_GLIBCXX_RELEASE)                && \
             _GLIBCXX_RELEASE > 4)))
#define HAVE_WORKING_REGEX 1
#else
#define HAVE_WORKING_REGEX 0
#endif
```

**Comment by jayeshkrishna** [comment]
The author of the post also indicates that the above macro (to detect if regex is supported) might become unusable since it uses internal definitions in the regex header (and no idea if it works with the IBM/PGI compilers).

For now we can just avoid regex for IBM and PGI compilers on Summit.
