### ISSUE TITLE
Scorpio asserts for non-NULL starts/counts when writing scalar variables

### ISSUE THREAD

**Issue by jayeshkrishna** [E3SM-Project/scorpio#373]
Scorpio asserts when the starts/counts are valid when writing out scalar variables. Although passing starts/counts don't make sense when writing out scalar variables libraries like NetCDF allow (and silently ignore) it.

From pio_getput_int.c
```
...
            if (ndims == 0)
            {
                /* This is a scalar var. */
                LOG((2, "pnetcdf writing scalar with ncmpi_put_vars_*() file->fh = %d varid = %d",
                     file->fh, varid));
                pioassert(!start && !count && !stride, "expected NULLs", __FILE__, __LINE__);
...
```

We will need to remove this assert and include a tighter check and warning to the user.

Also see E3SM-Project/E3SM#3988

**Comment by jayeshkrishna** [comment]
@dqwu : Any thoughts on this issue?

**Comment by dqwu** [comment]
> @dqwu : Any thoughts on this issue?

This is from legacy NCAR/ParallelIO code, see
https://github.com/NCAR/ParallelIO/commit/b44021ac72fc4eee01585f8dd4dab27d431fe04e

Your proposed fix looks good to me.
