### ISSUE TITLE
include <sstream>

### ISSUE THREAD

**Issue by rjdave** [E3SM-Project/scorpio#378]
Some systems require an include of _&lt;sstream&gt;_ in **tools/util/argparser.cxx** to define **std::stringstream**. I have run  into this on Mac OS Mojave using the Intel 19 compilers. It is the only system I have built SCORPIO on so far but I will update this issue if I find others.

**Comment by jayeshkrishna** [comment]
Thanks for reporting the issue, we will fix this in the code (include \<sstream\>)
