### ISSUE TITLE
netcdf4p support?

### ISSUE THREAD

**Issue by mt5555** [E3SM-Project/scorpio#394]
I get an error when trying to use 

ierr = PIO_CreateFile(PIOFS, FileID, PIO_iotype_netcdf4p, filename, PIO_64BIT_DATA)

This is in standalone HOMME, on Anvil, which builds with netcdf (netcdf-4.4.1-tckdgwl), but is NOT build with pnetcdf.

PIO: FATAL ERROR: Aborting... An error occured, Opening file (USGS-gtopo30_ne1024np4pg2_fx1t.nc) failed. Invalid io\
type (PIO_IOTYPE_PNETCDF:1) specified. Available iotypes are : PIO_IOTYPE_NETCDF (2). err=-500. 

When SCORPIO is compiled only netcdf and no pnetcdf, should we be able to use netcdf4p format?

**Comment by mt5555** [comment]
relevant cmake code: 
`
  if (${NetCDF_C_HAS_PARALLEL})
    set(PIO_USE_NETCDF4 1)
  else ()
    set(PIO_USE_NETCDF4 0)
  endif ()
`

**Comment by mt5555** [comment]
reading further, it appears to be possible to build NETCDF with HDF5, but without parallel support, which will then cause SCORPIO to compile without the NETCDF4 option.  Also, I read that HCF5 support in netcdf 4.4.1 up to 4.6.0 is buggy and should not be used, so perhaps it is good that this option cannot be enabled.

**Comment by dqwu** [comment]
> I wasn't reading the error carefully enough: now I see that the error is on the read of the input file (not creating the output file).
> 
> So this is a bug in HOMME - HOMME should not specify netcdf4p when opening a file for reading.

It seems that the HOMME test code is trying to open USGS-gtopo30_ne1024np4pg2_fx1t.nc with PIO_IOTYPE_PNETCDF. However, since SCORPIO is configured without PnetCDF support, you can not use PIO_IOTYPE_PNETCDF.

Available iotypes are : PIO_IOTYPE_NETCDF (2), which means PIO_IOTYPE_NETCDF4P (or PIO_IOTYPE_NETCDF4c) is also not supported for your configuration.
