### ISSUE TITLE
Use E3SM format for component names in Scorpio I/O performance stats 

### ISSUE THREAD

**Issue by jayeshkrishna** [E3SM-Project/scorpio#401]
We can use the E3SM format (used in E3SM configuration xml files) for component names when auto detecting components  while writing out the Scorpio I/O performance statistics.

As @rljacob suggested below the component name would be recorded as "COMP_\<E3SM COMPONENT NAME\> : \<SPECIFIC_MODEL_NAME\>".

|E3SM component name|Auto detected by Scorpio|New name (e.g.)|
|------|----|----|
|ATM|EAM|COMP_ATM : EAM|
|CPL|CPL|COMP_CPL : CPL|
|OCN|MPASO|COMP_OCN : MPASO|
|WAV||COMP_WAV : SWAV|
|GLC||COMP_GLC : SGLC|
|ICE|MPASSI|COMP_ICE : MPASSI|
|ROF|MOSART|COMP_ROF : MOSART|
|LND|ELM|COMP_LND : ELM|
|ESP||COMP_ESP : SESP|
|IAC||COMP_IAC : SIAC|

**Comment by rljacob** [comment]
You can the actual component name from vars in env_case.xml
COMP_OCN
COMP_LND
COMP_ATM
COMP_ICE
COMP_ROF
COMP_GLC
etc.
In a fully coupled case:
COMP_OCN: mpaso
COMP_ATM: eam
COMP_ICE: mpassi
COMP_ROF: mosart
COMP_CPL: cpl
