### ISSUE TITLE
Any reason to keep scorpio cmake minimum required version to 2.x?

### ISSUE THREAD

**Issue by bartgol** [E3SM-Project/scorpio#443]
CMake 2.x is somewhat "old". It precludes from using some of the more recent features, and can cause some warnings. E.g:
```
CMake Deprecation Warning at /home/luca/workdir/scream/scream-src/master/cime/tools/cprnc/CMakeLists.txt:14 (cmake_minimum_required):
  Compatibility with CMake < 2.8.12 will be removed from a future version of
  CMake.
```

Given that E3SM requires cmake 3.9, is there a reason for scorpio to still be stuck with 2.8.12?

**Comment by bartgol** [comment]
@dqwu @jayeshkrishna @rljacob , any reason not to move scorpio out of the 2.x cmake era?

**Comment by dqwu** [comment]
> @dqwu @jayeshkrishna @rljacob , any reason not to move scorpio out of the 2.x cmake era?

It is just a minimum requirement so far and actually most E3SM machines already use CMake 3.1x or higher.

**Comment by bartgol** [comment]
Right, but when CMake enters a subproject (like scorpio) that specifies a lower min version, it causes CMake to switch the default behavior of the policies to the new (lower) version, which may be different from what the host project expects.

**Comment by jayeshkrishna** [comment]
We can consider bumping up the min version required to match with E3SM.
@dqwu : Can you bump it up to the version required by E3SM (and test it out)?
