### ISSUE TITLE
Support large pids in GPTL

### ISSUE THREAD

**Issue by jayeshkrishna** [E3SM-Project/scorpio#453]
Ensure that the version of GPTL in SCORPIO supports large PIDs.

This is already fixed in the version of GPTL used in E3SM. The change required is to modify the check for the pid range from
```
GPTLget_memusage.c :  103
  if (pid > 999999) {
    fprintf (stderr, "get_memusage: pid %d is too large\n", pid);
    return -1;
  }
```
to
```
  if (pid <= 0) {
    fprintf (stderr, "get_memusage: pid %d is non-positive\n", pid);
    return -1;
  }
```

A better solution would be to get the latest version of GPTL from E3SM & add back all the custom SCORPIO fixes manually.

Note that E3SM builds use the E3SM version of GPTL and hence do not encounter this issue.

**Comment by dqwu** [comment]
The patch applied to the version of GPTL used in E3SM is:
https://github.com/E3SM-Project/E3SM/commit/adcde9e2ceafc9a14c1a82bbb6e46e4455a44a0c
