### ISSUE TITLE
C++ templates build errors on Crusher with Cray Clang compiler

### ISSUE THREAD

**Issue by dqwu** [E3SM-Project/scorpio#496]
For latest SCORPIO master branch, some C++ templates build errors can be reproduced on Crusher with the Cray Clang compiler (after loading craype-accel-amd-gfx90a, rocm/5.1.0 and setting the "-fopenmp" flag).

Step 1, load some modules on Crusher
```
. /usr/share/lmod/lmod/init/sh
module reset 
module load craype-accel-amd-gfx90a rocm/5.1.0
```

Step 2, build latest SCORPIO code with commands like below:
```
git clone https://github.com/E3SM-Project/scorpio.git
cd scorpio

mkdir build
cd build

CC=cc CXX=CC FC=ftn cmake -Wno-dev \
-DCMAKE_CXX_FLAGS="-fopenmp" \
-DWITH_NETCDF=OFF \
-DPnetCDF_PATH=/opt/cray/pe/parallel-netcdf/1.12.1.7/crayclang/10.0 \
-DPIO_USE_MALLOC=ON \
..

make
```

Build errors will be something like below:
```
[ 55%] Building CXX object src/clib/CMakeFiles/pioc.dir/spio_ltimer.cpp.o
In file included from /ccs/home/wuda/scorpio/src/clib/spio_ltimer.cpp:9:
In file included from /ccs/home/wuda/scorpio/src/clib/pio_internal.h:26:
In file included from /opt/cray/pe/cce/14.0.2/cce/x86_64/include/craylibs/math.h:5:
In file included from /opt/cray/pe/cce/14.0.2/cce-clang/x86_64/lib/clang/14.0.6/include/openmp_wrappers/math.h:20:
In file included from /opt/cray/pe/cce/14.0.2/cce-clang/x86_64/lib/clang/14.0.6/include/openmp_wrappers/cmath:21:
In file included from /opt/cray/pe/cce/14.0.2/cce/x86_64/include/craylibs/math.h:5:
In file included from /opt/cray/pe/cce/14.0.2/cce-clang/x86_64/lib/clang/14.0.6/include/openmp_wrappers/math.h:55:
In file included from /opt/cray/pe/cce/14.0.2/cce-clang/x86_64/lib/clang/14.0.6/include/__clang_hip_math.h:18:
In file included from /opt/cray/pe/gcc/10.3.0/snos/lib/gcc/x86_64-suse-linux/10.3.0/../../../../include/g++/algorithm:62:
In file included from /opt/cray/pe/gcc/10.3.0/snos/lib/gcc/x86_64-suse-linux/10.3.0/../../../../include/g++/bits/stl_algo.h:60:
/opt/cray/pe/gcc/10.3.0/snos/lib/gcc/x86_64-suse-linux/10.3.0/../../../../include/g++/bits/algorithmfwd.h:199:3: error: templates must have C++ linkage
  template<typename _IIter, typename _Predicate>
  ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
scorpio/src/clib/spio_ltimer.cpp:6:1: note: extern "C" language linkage specification begins here
extern "C"{
^
```

Comments:
1) This issue is **not reproducible** if -fopenmp is not contained in CMAKE_CXX_FLAGS
2) This issue is **not reproducible** if craype-accel-amd-gfx90a rocm/5.1.0 modules are not loaded

**Comment by rljacob** [comment]
So is C99 support broken in this compiler?

**Comment by dqwu** [comment]
> So is C99 support broken in this compiler?

No, C99 support is not broken for Cray Clang on Crusher.

**Comment by dqwu** [comment]
@jayeshkrishna @rljacob 
There are two unrelated issues confirmed so far.

Issue 1 (enum error)
 A potential bug in GPTL's private.h file (in both SCORPIO's internal GPTL lib and E3SM's GPTL lib)
```
#ifndef __cplusplus
typedef enum {false = 0, true = 1} bool;  /* mimic C++ */
#endif
```
If the compiler wrappers implicitly include stdbool.h (has macro definitions of true and false) when compiling this code block, macro expansions will cause build errors: enum {0 = 0, 1 = 1}

To fix this issue, we can replace this existing enum definition with explicit inclusion of stdbool.h
Or we can check whether true (or false, or both) has been defined (e.g. by stdbool.h) before defining the new enum type
```
# ifndef true
typedef enum {false = 0, true = 1} bool;  /* mimic C++ */
# endif
```

Issue 2 (C++ template template error)
@ambrad has some comments:
The issue is lines like this in, for example, spio_ltimer.cpp:
```
extern "C"{                                                                                                                                                                                                                                       
#include "pio_config.h"
#include "pio.h"
#include "pio_internal.h"
#include "spio_ltimer.h"
}
```

the issue is that __cplusplus is still defined, so in the inclusion
stack starting from pio_internal.hpp, there is a clang header,
__clang_hip_math.h, whose __cplusplus logic gets defeated. 
extern'ing around the header inclusions is, 
i'm pretty sure, completely unnecessary here b/c the h files already
establish C linkage.

In file included from /autofs/nccs-svm1_home1/ambradl/repo/SCREAM/externals/scorpio/src/clib/spio_file_mvcache.cpp:9:            
```
<--- PIO file that wraps pio_internal.h with extern "C"
In file included from /autofs/nccs-svm1_home1/ambradl/repo/SCREAM/externals/scorpio/src/clib/pio_internal.h:26:                  <--- last app-side include, now externed as C
In file included from /opt/cray/pe/cce/14.0.0/cce/x86_64/include/craylibs/math.h:5:
In file included from /opt/cray/pe/cce/14.0.0/cce-clang/x86_64/lib/clang/14.0.0/include/openmp_wrappers/math.h:20:               <--- openmp-dependent inclusion from cray wrapper's use of clang
In file included from /opt/cray/pe/cce/14.0.0/cce-clang/x86_64/lib/clang/14.0.0/include/openmp_wrappers/cmath:21:
In file included from /opt/cray/pe/cce/14.0.0/cce/x86_64/include/craylibs/math.h:5:
In file included from /opt/cray/pe/cce/14.0.0/cce-clang/x86_64/lib/clang/14.0.0/include/openmp_wrappers/math.h:55:
In file included from /opt/cray/pe/cce/14.0.0/cce-clang/x86_64/lib/clang/14.0.0/include/__clang_hip_math.h:18:                   <--- uses __cplusplus symbol, broken by PIO's extern "C" wrapping
```

in the last line, __cplusplus is defined, so __clang_hip_math.h includes a C++ header. that brings a C++ header into PIO's extern "C" wrapping, which of course won't work.

**Comment by jayeshkrishna** [comment]
The issue with the private.h (in GPTL library) seems to be related to using the "-fopenmp" flag with the "craype-accel-amd-gfx90a & rocm/5.1.0" modules as noted above by @dqwu . Like @dqwu noted in the related slack conversation it looks like the compiler is implicitly including stdbool.h in this case.
The issue can be recreated using the following C example (bool.c),
```
enum {false = 0};

int main(int argc, char *argv[])
{
  return 0;
}

```
If the code, bool.c, above is built using the script below it shows the error,
```
#!/bin/tcsh
source /usr/share/lmod/lmod/init/csh

module reset
module switch PrgEnv-cray PrgEnv-cray/8.3.3
module switch cce cce/14.0.0

module load craype-accel-amd-gfx90a
module load rocm/5.1.0

cc -fopenmp bool.c -o bool

```
However, if the same code, bool.c, is built using the script below it does not show any errors,
```
#!/bin/tcsh
source /usr/share/lmod/lmod/init/csh

module reset
module switch PrgEnv-cray PrgEnv-gnu/8.3.3

cc -fopenmp bool.c -o bool

```

**Comment by jayeshkrishna** [comment]
Like @ambrad noted in his slack conversations, the second issue related to extern "C" linkage is due to math.h being included from a C++ source inside an extern "C" block. When OpenMP is enabled for the cray compiler, including math.h from a C++ source results in cmath and other C++ headers with templates being included, and these templates require C++ linkage (that contradicts the extern "C" linkage specified for the header hierarchy).
Header files like math.h use the "__cplusplus" preproc definition to decide if the source including the header file is C++ or C (& includes the C++ header files accordingly),
```
...
#ifdef __cplusplus
#include <cmath>
#endif

...
```
A simple example, inclmath.cpp, below can recreate this issue,
```
extern "C"{
#include <math.h>
}

int main(int argc, char *argv[])
{
  return 0;
}

```
If the source, inclmath.cpp, above is built using the script below we can recreate the issue,
```
#!/bin/tcsh
source /usr/share/lmod/lmod/init/csh

module reset
module switch PrgEnv-cray PrgEnv-cray/8.3.3
module switch cce cce/14.0.0

module load craype-accel-amd-gfx90a
module load rocm/5.1.0

CC -fopenmp inclmath.cpp -o inclmath

```
Note that removing the "-fopenmp" flag or removing the amd/rocm modules gets the code building correctly again,
```
#!/bin/tcsh
source /usr/share/lmod/lmod/init/csh

module reset
module switch PrgEnv-cray PrgEnv-cray/8.3.3
module switch cce cce/14.0.0

CC -fopenmp inclmath.cpp -o inclmath

```

**Comment by jayeshkrishna** [comment]
I will work on a PR to change SCORPIO code to workaround the issues above,

1. For the issue with predefined boolean variables in private.h (in GPTL) we can move GPTL in SCORPIO to require C99 (like the rest of the library) and include stdbool.h. Thanks @oksanaguba for the pointers
2. For the issue with math.h including templated headers from an extern "C" block we can move the extern "C" blocks to header files as suggested by @ambrad . It is more robust to make the header files work with C & C++ code without having to use the extern block (move the extern "C" block inside the header files to cover all required function decls). I will add a slightly modified version of the patch suggested by @ambrad .

Thanks @oksanaguba & @ambrad for the patches.
