### ISSUE TITLE
use scorpio in cesm-ihesp-hires1.0.47

### ISSUE THREAD

**Issue by xiaohumengdie** [E3SM-Project/scorpio#579]
Hello,
I tried to use scorpio adios output in ihesp-hires1.0.47(https://github.com/ihesp/cesm/tree/cesm-ihesp-hires1.0.47), run it for five days, and then write restart file. Compared to output using pnetcdf, all the other restart files were consistent except the clm2.r restart file. the cprnc log:

SUMMARY of cprnc:
 A total number of    163 fields were compared
          of which      3 had non-zero differences
               and      0 had differences in fill patterns
               and      0 had different dimension sizes
 A total number of      2 fields could not be analyzed
 A total number of      0 fields on file 1 were not found on file 2.
 A total number of      0 fields on file 2 were not found on file 1.
  diff_test: the two files seem to be DIFFERENT

``
the software stacks is oneAPI2023.0.0.25400, pnetcdf-1.11.2, hdf5-1_13_3,ADIOS2-2.9.1,netcdf-c-4.9.1-rc1,netcdf-fortran-4.6.0 ,scorpio-v1.6.1
``

**Comment by jayeshkrishna** [comment]
Thank you for reporting the issue. We haven't tried SCORPIO with CESM in a while (PIO is the recommended/supported I/O library for CESM).
Meanwhile, please use PnetCDF for LND component in your runs (./xmlchange PIO_TYPENAME_LND=pnetcdf)
