### ISSUE TITLE
Consolidate author info to README

### ISSUE THREAD

**Issue by jayeshkrishna** [E3SM-Project/scorpio#99]
Consolidate all author info from function documentations
to README.

Git already has info on the author. Remove @author tags
in the function documentation and add a list of developers
contributing/contributed to PIO in the README .

**Comment by edhartnett** [comment]
Usually other programmers don't try to strip my name out of the code that I have written. While technically permissible, this is outside the bounds of normal free software culture. Programmers are usually given credit for their work.

@jayeshkrishna @dqwu can we discuss this issue please?

My first concern is that the scientists on E3SM understand what they are getting, and where it came from.

My second concern is that this derived product not be released to the general public as someone else's work. @jedwards and I deserve credit for our work, as is traditional in scientific work.

**Comment by jayeshkrishna** [comment]
Sorry we decided months ago not to do this and forgot to close it
